[[imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"

[[mounts]]
    source = "content/zh"
    target = "content"

    [mounts.sites.matrix]
        languages = ["zh"]

[[mounts]]
    source = "content/en"
    target = "content"

    [mounts.sites.matrix]
        languages = ["en"]

[[mounts]]
    source = "content/private"
    target = "content"
    files = [
        "! _templates/**",
        "! journal/**",
        "! LOG.md",
        "! README.md",
        "! post/archives/**",
        "! post/INBOX.md",
    ]

    [mounts.sites.matrix]
        languages = ["private"]
